import { TaskProvider } from "@/context/TasksContext";
import NavbarMenu from "@/components/Navbar/Nav";
import "./globals.css";

export const metadata = {
  title: "Proyecto de NextJs con ejercicios de React",
  description: "Generated by Rzaldumbide",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <TaskProvider>
          <NavbarMenu />
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
