import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Proyecto de NextJs con ejercicios de React",
  description: "Generated by Rzaldumbide",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <main className="container my-3 justify-center p-10 mx-auto min-h-screen" >
          {children}
        </main>
      </body>
    </html>
  );
}
