import { Providers } from "./providers";
import "./globals.css";
import NavbarMenu from "@/components/Navbar/Nav";

export const metadata = {
  title: "Proyecto de NextJs con ejercicios de React",
  description: "Generated by Rzaldumbide",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" >
      <body >
        <NavbarMenu />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
